### ISSUE TITLE
Missing Funds 

### ISSUE THREAD

**Issue by beaudown** [coschain/contentos-go#12] opened 2020-09-06 17:46 UTC
I paid 15 dollars for xrp traded them for COS and then had them swapped by youir official website. The Cos never showed up. I tried going to Cos wallet website and now i realize i dont have a private key or mnemonic code. How did i make an account and not get the codes? I make screenshots and attatch them to notes for my crypto wallets and I do not have anything for this account. Very upset there is no repsonse from the app support. THIS IS REAL MONEY I spent to put into this account. It's gone never showed up on the block chain. Not that it matters I cant access the wallet for anything else anyway without the keys!! so do i just delete my cos tv account? with all my followers and try again?
![Screenshot_20200831-005011_Gmail](https://user-images.githubusercontent.com/65331815/92331817-2c436e80-f02e-11ea-9f86-5317d436064e.png)
![Screenshot_20200831-004943_Gmail](https://user-images.githubusercontent.com/65331815/92331818-32394f80-f02e-11ea-91bb-09b6490fc3bc.png)
![Screenshot_20200831-005147](https://user-images.githubusercontent.com/65331815/92331822-37969a00-f02e-11ea-9811-401cb66a4343.png)

**Comment by dai-shuo** [comment] 2020-12-29 10:38
hi @beaudown 

I read the transactions in your screenshots,
http://explorer.contentos.io/#/tx/deeada47bab3f04b115964ab0f96b707f347d7629da3d5db2b61390add88728d
http://explorer.contentos.io/#/tx/34753f9dfee75f3c478bb60cc8a1f0800554e5f7b3bb8bb6af2f2636a4d27142

I guess you intended to transfer cos from bitrue exchange to your main-net account. But the trxs were actually telling the token-swap service to deposite cos tokens to one of contentos official binance BEP2 accounts. Both chains, contentos and binance dex, worked exactly as expected. I believe it was a mistaken use of bitrue withdrawal.

This issue has been forwarded to token-swap guys. You may get your cos back once they confirmed it.

I'll close this issue since it's not related to any flaws of contentos main-net.

**Comment by dai-shuo** [comment] 2020-12-29 10:39
Not an issue of Contentos blockchain.

**Closed as completed** 2020-12-29 10:38 UTC

**Comment by beaudown** [comment] 2020-12-29 16:20
> Not an issue of Contentos blockchain.

I was never given access to my Contentos wallet private keys.

**Comment by dai-shuo** [comment] 2020-12-30 05:31
> > Not an issue of Contentos blockchain.
> 
> I was never given access to my Contentos wallet private keys.

You're using [cos.tv](https://cos.tv/). The website and Contentos blockchain are connected but different systems. [cos.tv](https://cos.tv/) is an agent, it hosts your private key so that it can put your actions on the Contentos blockchain in your behalf. 

cos.tv users have no access to their private keys, otherwise, transactions are no longer undeniable. You can get your private key by using the "unbind" feature of cos.tv. After unbinding, cos.tv allows you to watch videos but no comments nor votes.

So it's all about cos.tv, not the underlying Contentos blockchain. 
Hope this makes it clearer.
